version: "3.9"
services:
  provider:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:7.1.0
    container_name: provider
    networks:
      ba:
        ipv4_address: 172.21.1.10
  consumer:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:7.1.0
    container_name: consumer
    networks:
      ba:
        ipv4_address: 172.21.1.20

networks:
  ba:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.1.0/24