version: "3.9"
services:
  provider:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:7.1.0
    container_name: providerPLACEHOLDER_SUBNETID
    networks:
      baPLACEHOLDER_SUBNETID:
  consumer:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:7.1.0
    container_name: consumerPLACEHOLDER_SUBNETID
    networks:
      baPLACEHOLDER_SUBNETID:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-serverPLACEHOLDER_SUBNETID
    environment:
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=PLACEHOLDER_SSH_PASS
      - USER_NAME=PLACEHOLDER_SSH_USER
    volumes:
      - ./ssh-workaround/88-enable_forwarding:/etc/cont-init.d/88-enable_forwarding:ro
      # # - /etc/hosts:/etc/hosts:ro
    networks:
      baPLACEHOLDER_SUBNETID:
        ipv4_address: 172.23.PLACEHOLDER_SUBNETID.22

  colab-local:
    build: ./colab-local-runtime-docker
    container_name: colab-localPLACEHOLDER_SUBNETID
    networks:
      baPLACEHOLDER_SUBNETID:
        ipv4_address: 172.23.PLACEHOLDER_SUBNETID.88

networks:
  baPLACEHOLDER_SUBNETID:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.PLACEHOLDER_SUBNETID.0/24