PROVIDE_ACCESS="PROVIDE_ACCESS"
DURATION_USAGE="DURATION_USAGE"
USAGE_DURING_INTERVAL="USAGE_DURING_INTERVAL"
USAGE_UNTIL_DELETION="USAGE_UNTIL_DELETION"

PROHIBIT_ACCESS="PROHIBIT_ACCESS"
OTHER_PATTERN="OTHER_PATTERN"