version: "3.0"
services:
  providerPLACEHOLDER_SUBNETID:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:7.1.0
    container_name: providerPLACEHOLDER_SUBNETID
    networks:
      baPLACEHOLDER_SUBNETID:
        ipv4_address: 172.23.PLACEHOLDER_SUBNETID.10
  consumerPLACEHOLDER_SUBNETID:
    image: ghcr.io/international-data-spaces-association/dataspace-connector:7.1.0
    container_name: consumerPLACEHOLDER_SUBNETID
    networks:
      baPLACEHOLDER_SUBNETID:
  openssh-serverPLACEHOLDER_SUBNETID:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-serverPLACEHOLDER_SUBNETID
    environment:
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=PLACEHOLDER_SSH_PASS
      - USER_NAME=PLACEHOLDER_SSH_USER
    volumes:
      - ./ssh-workaround/88-enable_forwarding:/etc/cont-init.d/88-enable_forwarding:ro
      - ./ssh-workaround/banner:/etc/banner:ro
      # # - /etc/hosts:/etc/hosts:ro
    network_mode: service:colab-localPLACEHOLDER_SUBNETID
    depends_on:
      - colab-localPLACEHOLDER_SUBNETID
  colab-localPLACEHOLDER_SUBNETID:
    build: ./colab-local-runtime-docker
    container_name: colab-localPLACEHOLDER_SUBNETID
    ports:
      - PLACEHOLDER_SSH_PORT:2222
    networks:
      baPLACEHOLDER_SUBNETID:
        ipv4_address: 172.23.PLACEHOLDER_SUBNETID.22

networks:
  baPLACEHOLDER_SUBNETID:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.PLACEHOLDER_SUBNETID.0/24